### ISSUE TITLE
Infinite recursion when filtering

### ISSUE THREAD

**Issue by LKlinke** [LKlinke/Prodigy#4]
```python
from prodigy.distribution import GeneratingFunction, SympyPGF

gf = GeneratingFunction("(1-sqrt(1-c**2))/c")
assert gf.filter(parse_expr("x*z <= 10")) == SympyPGF.zero()
```

yields in infinite recursion

**Comment by Legotier** [comment]
The problem was that the right hand side of the condition does not contain any variables. This means that the marginal computed in `_explicit_state_unfolding` was simply `1` (without any variables). This again meant that there was only one `State` in the marginal, namely the empty state (with coefficient `1`). The function `_state_to_equality_expression` returned `True` if it was passed the empty state (which in theory makes sense, because the empty conjunction is defined as true). But since there was only one state, the entire `_explicit_state_unfolding` function simply returned `True` in conjunction with the original condition - which was used again as a parameter for `filter`, and everything started anew.

The solution I implemented was to simply use the marginal of the other side of the expression in this case. This lead to another problem with symbols that aren't variables or parameters of the generating function, which is why I added an explicit check for this case.
